/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Final1.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Final1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bottleBody.geometry} material={materials['lotion_container_01.001']} />
      <mesh geometry={nodes.frontLable.geometry} material={materials['labels_bottle_01.001']} />
      <mesh geometry={nodes.bottleCap.geometry} material={materials.black} />
      <mesh geometry={nodes.extraLable.geometry} material={materials['Material.001']} position={[0, 0, 0.98]} />
      <mesh geometry={nodes.backLable.geometry} material={materials['Material.007']} position={[0, 0, -0.01]} />
      <mesh geometry={nodes.bottomText.geometry} material={materials.black} position={[0, -9.255, 0.133]} rotation={[0, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Final1.gltf')
