/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kerabotoxanimation.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/kerabotoxanimation.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Moisturizing_Lotion_Container_Type_01_Pose_01_Blank_Group" position={[0, -7.56, 0]}>
          <mesh name="bottle_part01" geometry={nodes.bottle_part01.geometry} material={materials['lotion_container_01.001']} position={[0, 8.987, 0]} />
          <mesh name="label_top_part02" geometry={nodes.label_top_part02.geometry} material={materials['lotion_container_01.001']} position={[0, 8.987, 0]} />
          <mesh name="labels_part03" geometry={nodes.labels_part03.geometry} material={materials['labels_bottle_01.001']} position={[0, 8.987, 0]} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/kerabotoxanimation.glb");
