/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 newAnim.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/newAnim.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Moisturizing_Lotion_Container_Type_01_Pose_01_Blank_Group">
          <mesh name="bottle_part01" geometry={nodes.bottle_part01.geometry} material={materials['Realistic_Glass_Bottle.001']} position={[0, 8.987, 0]} />
          <mesh name="label_top_part02" geometry={nodes.label_top_part02.geometry} material={materials['Material.001']} position={[0, 8.987, 0]} />
          <mesh name="labels_part03" geometry={nodes.labels_part03.geometry} material={materials['labels_bottle_01.001']} position={[0, 8.987, 0]} rotation={[-Math.PI, 0.006, -Math.PI]} />
        </group>
        <mesh name="Shampoo_Source" geometry={nodes.Shampoo_Source.geometry} material={materials['Shampoo_Material.001']} position={[0, 6.68, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-14.88, -126.97, -5.42]} />
        <mesh name="Fluid_Domain" geometry={nodes.Fluid_Domain.geometry} material={nodes.Fluid_Domain.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/newAnim.gltf')
