/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\normalBottle.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/normalBottle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bottle_part01.geometry} material={materials['lotion_container_01.001']} />
      <mesh geometry={nodes.label_top_part02.geometry} material={materials.black} />
      <mesh geometry={nodes.label_top_part02001.geometry} material={materials.black} />
      <mesh geometry={nodes.labels_part03.geometry} material={materials['labels_bottle_01.001']} />
      <mesh geometry={nodes.labels_part03001.geometry} material={materials['Material.001']} position={[0, 0, -0.01]} />
    </group>
  )
}

useGLTF.preload('/normalBottle.glb')
