/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\bottle_final_with_names.glb 
*/

import React, { forwardRef } from 'react'

import { useGLTF } from '@react-three/drei'

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('./bottle_final_with_names.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.backLable.geometry} material={materials.Nanoplast} position={[0, 0, -0.01]} />
      <mesh geometry={nodes.bottleBody.geometry} material={materials['lotion_container_01.001']} />
      <mesh geometry={nodes.bottleCap.geometry} material={materials.black} />
      <mesh geometry={nodes.bottomText.geometry} material={materials.black} position={[0, -9.255, 0.133]} rotation={[0, 0, Math.PI]} />
      <mesh geometry={nodes.extraLable.geometry} material={materials.keratin} position={[0, 0, 0.98]} />
      <mesh geometry={nodes.frontLable.geometry} material={materials.kerabotox} />
    </group>
  )
})
export default Model
Model.displayName = 'Bottle_final_with_names'
useGLTF.preload('./bottle_final_with_names.glb')
