/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Final1.glb 
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/Final1.glb')
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.bottle_part01.geometry} material={materials['lotion_container_01.001']} />
      <mesh geometry={nodes.labels_part03.geometry} material={materials['labels_bottle_01.001']} />
      <mesh geometry={nodes.label_top_part02001.geometry} material={materials.black} />
      <mesh geometry={nodes.labels_part03001.geometry} material={materials['Material.001']} position={[0, 0, 0.98]} />
      <mesh geometry={nodes.labels_part03002.geometry} material={materials['Material.007']} position={[0, 0, -0.01]} />
      <mesh geometry={nodes.Text.geometry} material={materials.black} position={[0, -9.255, 0.133]} rotation={[0, 0, Math.PI]} />
    </group>
  )
})
export default Model

useGLTF.preload('/Final1.glb')
