/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\normal3bottle.glb 
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/normal3bottle.glb')
  // print all the avaliable materials
  console.log(materials);
  
  return (
    <group ref={ref} {...props} dispose={null} userData={{ materials }}>
      <mesh name="bottle_part01" geometry={nodes.bottle_part01.geometry} material={materials['lotion_container_01.001']} />
      <mesh name="label_top_part02" geometry={nodes.label_top_part02.geometry} material={materials.black} />
      <mesh name="label_top_part02001" geometry={nodes.label_top_part02001.geometry} material={materials.black} />
      <mesh name="labels_part03" geometry={nodes.labels_part03.geometry} material={materials['labels_bottle_01.001']} />
      <mesh name="labels_part03001" geometry={nodes.labels_part03001.geometry} material={materials['Material.001']} position={[0, 0, -0.01]} />
    </group>
  )
})

Model.displayName = 'Normal3bottle'

export default Model

useGLTF.preload('/normal3bottle.glb')
